version: '2'

services:
    user-db:
        build:
            context: ./docker/user-db/
        image: weaveworksdemos/user-db-jenkins
        hostname: user-db
        restart: always
        cap_drop:
            - all
        cap_add:
            - CHOWN
            - SETGID
            - SETUID
        read_only: true
        tmpfs:
            - /tmp:rw,noexec,nosuid
        environment:
            - reschedule=on-node-failure
        ports:
            - "27017:27017"
